



  Performance statistics for DSP solver: icalls =     47

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            1260
     no. of nonzeroes in lower triangle of a =           18054
     no. of nonzeroes in the factor l        =           63354
     ratio of nonzeroes in factor (min/max)  =          0.9199
     number of super nodes                   =              65
     maximum order of a front matrix         =              78
     maximum size of a front matrix          =            3081
     maximum size of a front trapezoid       =            2415
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      2.4983D+06
     no. of floating point ops for solve     =      2.0558D+05
     ratio of flops for factor (min/max)     =          0.7969
     ratio of allocated memory (max/min)     =          1.0464
     number of positive pivots               =            1260
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000087
     time (cpu & wall) for matrix distrib.   =        0.000000        0.001909
     time (cpu & wall) for numeric factor    =        0.015625        0.014022
     computational rate (gflops) for factor  =        0.159894        0.178177

     no input or output performed

  Solver Memory allocated on core    0       =        0.555 MB
  Solver Memory allocated on core    1       =        0.581 MB
  Solver Memory allocated on core    2       =        0.565 MB
  Solver Memory allocated on core    3       =        0.558 MB
  Total Solver Memory allocated by all cores =        2.259 MB

