



  Performance statistics for DSP solver: icalls =     49

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            4140
     no. of nonzeroes in lower triangle of a =           62358
     no. of nonzeroes in the factor l        =          274492
     ratio of nonzeroes in factor (min/max)  =          0.9369
     number of super nodes                   =             193
     maximum order of a front matrix         =             112
     maximum size of a front matrix          =            6328
     maximum size of a front trapezoid       =            4498
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      1.4809D+07
     no. of floating point ops for solve     =      9.2092D+05
     ratio of flops for factor (min/max)     =          0.9151
     ratio of allocated memory (max/min)     =          1.0538
     number of positive pivots               =            4135
     number of negative pivots               =               5
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000275
     time (cpu & wall) for matrix distrib.   =        0.000000        0.001257

     no input or output performed

  Solver Memory allocated on core    0       =        1.567 MB
  Solver Memory allocated on core    1       =        1.515 MB
  Solver Memory allocated on core    2       =        1.563 MB
  Solver Memory allocated on core    3       =        1.487 MB
  Total Solver Memory allocated by all cores =        6.133 MB

